name: lifely
description: A Simple Life Tracking App

publish_to: 'none'

version: 2.0.0

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.1.0
  community_material_icon: ^5.9.55
  status_alert: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true